apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage-mongo-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
