apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: datastore
  name: datastore
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: datastore
    spec:
      containers:
      - args:
        - mongod
        - --logpath=/dev/null
        env:
        - name: MONGO_DATA_DIR
          value: /data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: mongo
        name: datastore
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: datastore-claim0
      restartPolicy: Always
      volumes:
      - name: datastore-claim0
        persistentVolumeClaim:
          claimName: datastore-claim0
status: {}
