apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: micro
  name: micro
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: micro
    spec:
      containers:
      - args:
        - api
        - --enable_rpc
        env:
        - name: MICRO_REGISTRY
          value: mdns
        image: microhq/micro
        name: micro
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
