apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: micro
  name: micro
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: micro
status:
  loadBalancer: {}
