apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: shippy-ui
  name: shippy-ui
spec:
  type: LoadBalancer
  ports:
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: shippy-ui
