apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: shippy-service-vessel
  name: shippy-service-vessel
spec:
  ports:
  - name: "50052"
    port: 50052
    targetPort: 50051
  selector:
    io.kompose.service: shippy-service-vessel
status:
  loadBalancer: {}
