apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: shippy-server
  name: shippy-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: shippy-server
    spec:
      containers:
      - image: shippy-server:v2
        imagePullPolicy: IfNotPresent
        name: shippy-server
        resources: {}
      restartPolicy: Always
status: {}
